//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheonixRt.Mvvm.MeshingManagerServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MeshingManagerServiceReference1.IMeshingManager")]
    public interface IMeshingManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMeshingManager/MeshStructure")]
        void MeshStructure(PheonixRt.MeshingServiceContracts.MeshingRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeshingManagerChannel : PheonixRt.Mvvm.MeshingManagerServiceReference1.IMeshingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeshingManagerClient : System.ServiceModel.ClientBase<PheonixRt.Mvvm.MeshingManagerServiceReference1.IMeshingManager>, PheonixRt.Mvvm.MeshingManagerServiceReference1.IMeshingManager {
        
        public MeshingManagerClient() {
        }
        
        public MeshingManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeshingManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeshingManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeshingManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MeshStructure(PheonixRt.MeshingServiceContracts.MeshingRequest request) {
            base.Channel.MeshStructure(request);
        }
    }
}
