//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageRenderManagerService.MprEngineServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MprEngineServiceReference1.IMprGenerationEngineService")]
    public interface IMprGenerationEngineService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMprGenerationEngineService/GenerateMpr")]
        void GenerateMpr(MprGenerationContracts.MprGenerationRequestV1 request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMprGenerationEngineServiceChannel : ImageRenderManagerService.MprEngineServiceReference1.IMprGenerationEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MprGenerationEngineServiceClient : System.ServiceModel.ClientBase<ImageRenderManagerService.MprEngineServiceReference1.IMprGenerationEngineService>, ImageRenderManagerService.MprEngineServiceReference1.IMprGenerationEngineService {
        
        public MprGenerationEngineServiceClient() {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MprGenerationEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateMpr(MprGenerationContracts.MprGenerationRequestV1 request) {
            base.Channel.GenerateMpr(request);
        }
    }
}
