//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheonixRt.Mvvm.MprGenerationEngineServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MprGenerationRequestV1", Namespace="http://schemas.datacontract.org/2004/07/MprGenerationEngine")]
    [System.SerializableAttribute()]
    public partial class MprGenerationRequestV1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImageVolumeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PheonixRt.Mvvm.MprGenerationEngineServiceReference1.Orientation OrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SlicePositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WindowCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WindowWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImageVolumeId {
            get {
                return this.ImageVolumeIdField;
            }
            set {
                if ((this.ImageVolumeIdField.Equals(value) != true)) {
                    this.ImageVolumeIdField = value;
                    this.RaisePropertyChanged("ImageVolumeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PheonixRt.Mvvm.MprGenerationEngineServiceReference1.Orientation Orientation {
            get {
                return this.OrientationField;
            }
            set {
                if ((this.OrientationField.Equals(value) != true)) {
                    this.OrientationField = value;
                    this.RaisePropertyChanged("Orientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestTime {
            get {
                return this.RequestTimeField;
            }
            set {
                if ((this.RequestTimeField.Equals(value) != true)) {
                    this.RequestTimeField = value;
                    this.RaisePropertyChanged("RequestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SlicePosition {
            get {
                return this.SlicePositionField;
            }
            set {
                if ((this.SlicePositionField.Equals(value) != true)) {
                    this.SlicePositionField = value;
                    this.RaisePropertyChanged("SlicePosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WindowCenter {
            get {
                return this.WindowCenterField;
            }
            set {
                if ((this.WindowCenterField.Equals(value) != true)) {
                    this.WindowCenterField = value;
                    this.RaisePropertyChanged("WindowCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WindowWidth {
            get {
                return this.WindowWidthField;
            }
            set {
                if ((this.WindowWidthField.Equals(value) != true)) {
                    this.WindowWidthField = value;
                    this.RaisePropertyChanged("WindowWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orientation", Namespace="http://schemas.datacontract.org/2004/07/MprGenerationEngine")]
    public enum Orientation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transverse = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Coronal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sagittal = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MprGenerationEngineServiceReference1.IMprGenerationEngineService")]
    public interface IMprGenerationEngineService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMprGenerationEngineService/GenerateMpr")]
        void GenerateMpr(PheonixRt.Mvvm.MprGenerationEngineServiceReference1.MprGenerationRequestV1 request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMprGenerationEngineServiceChannel : PheonixRt.Mvvm.MprGenerationEngineServiceReference1.IMprGenerationEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MprGenerationEngineServiceClient : System.ServiceModel.ClientBase<PheonixRt.Mvvm.MprGenerationEngineServiceReference1.IMprGenerationEngineService>, PheonixRt.Mvvm.MprGenerationEngineServiceReference1.IMprGenerationEngineService {
        
        public MprGenerationEngineServiceClient() {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MprGenerationEngineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MprGenerationEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateMpr(PheonixRt.Mvvm.MprGenerationEngineServiceReference1.MprGenerationRequestV1 request) {
            base.Channel.GenerateMpr(request);
        }
    }
}
