//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheonixRt.Mvvm.DicomScanServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DicomScanServiceReference1.IDicomScanManager")]
    public interface IDicomScanManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDicomScanManager/ScanDirectory")]
        void ScanDirectory(string pathname, bool rescan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDicomScanManagerChannel : PheonixRt.Mvvm.DicomScanServiceReference1.IDicomScanManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DicomScanManagerClient : System.ServiceModel.ClientBase<PheonixRt.Mvvm.DicomScanServiceReference1.IDicomScanManager>, PheonixRt.Mvvm.DicomScanServiceReference1.IDicomScanManager {
        
        public DicomScanManagerClient() {
        }
        
        public DicomScanManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DicomScanManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DicomScanManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DicomScanManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ScanDirectory(string pathname, bool rescan) {
            base.Channel.ScanDirectory(pathname, rescan);
        }
    }
}
