//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheonixRt.Mvvm.LocalGeometryResourceServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalGeometryResourceServiceReference1.ILocalGeometryResourceManager")]
    public interface ILocalGeometryResourceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetStructureResourceIds", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetStructureResourceIdsResponse")]
        System.Collections.Generic.List<System.Guid> GetStructureResourceIds(string patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetStructuresInFrameOfReferenceU" +
            "id", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetStructuresInFrameOfReferenceU" +
            "idResponse")]
        System.Collections.Generic.List<System.Guid> GetStructuresInFrameOfReferenceUid(string forUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetStructure", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetStructureResponse")]
        PheonixRt.DataContracts.StructureDataContract GetStructure(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/AddStructure", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/AddStructureResponse")]
        PheonixRt.DataContracts.StructureDataContract AddStructure(PheonixRt.DataContracts.StructureDataContract sdc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/RemoveStructure", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/RemoveStructureResponse")]
        void RemoveStructure(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/AddPolygon", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/AddPolygonResponse")]
        PheonixRt.DataContracts.ContourDataContract AddPolygon(PheonixRt.DataContracts.ContourDataContract pdc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetPolygon", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetPolygonResponse")]
        PheonixRt.DataContracts.ContourDataContract GetPolygon(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetSurfaceMesh", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetSurfaceMeshResponse")]
        PheonixRt.DataContracts.SurfaceMeshDataContract GetSurfaceMesh(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/GetSurfaceMeshByRelatedStructure" +
            "Id", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/GetSurfaceMeshByRelatedStructure" +
            "IdResponse")]
        PheonixRt.DataContracts.SurfaceMeshDataContract GetSurfaceMeshByRelatedStructureId(System.Guid relatedId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/AddSurfaceMesh", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/AddSurfaceMeshResponse")]
        PheonixRt.DataContracts.SurfaceMeshDataContract AddSurfaceMesh(PheonixRt.DataContracts.SurfaceMeshDataContract sdc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalGeometryResourceManager/RemoveSurfaceMesh", ReplyAction="http://tempuri.org/ILocalGeometryResourceManager/RemoveSurfaceMeshResponse")]
        void RemoveSurfaceMesh(System.Guid guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocalGeometryResourceManagerChannel : PheonixRt.Mvvm.LocalGeometryResourceServiceReference1.ILocalGeometryResourceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalGeometryResourceManagerClient : System.ServiceModel.ClientBase<PheonixRt.Mvvm.LocalGeometryResourceServiceReference1.ILocalGeometryResourceManager>, PheonixRt.Mvvm.LocalGeometryResourceServiceReference1.ILocalGeometryResourceManager {
        
        public LocalGeometryResourceManagerClient() {
        }
        
        public LocalGeometryResourceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalGeometryResourceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalGeometryResourceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalGeometryResourceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Guid> GetStructureResourceIds(string patientId) {
            return base.Channel.GetStructureResourceIds(patientId);
        }
        
        public System.Collections.Generic.List<System.Guid> GetStructuresInFrameOfReferenceUid(string forUid) {
            return base.Channel.GetStructuresInFrameOfReferenceUid(forUid);
        }
        
        public PheonixRt.DataContracts.StructureDataContract GetStructure(System.Guid id) {
            return base.Channel.GetStructure(id);
        }
        
        public PheonixRt.DataContracts.StructureDataContract AddStructure(PheonixRt.DataContracts.StructureDataContract sdc) {
            return base.Channel.AddStructure(sdc);
        }
        
        public void RemoveStructure(System.Guid guid) {
            base.Channel.RemoveStructure(guid);
        }
        
        public PheonixRt.DataContracts.ContourDataContract AddPolygon(PheonixRt.DataContracts.ContourDataContract pdc) {
            return base.Channel.AddPolygon(pdc);
        }
        
        public PheonixRt.DataContracts.ContourDataContract GetPolygon(System.Guid guid) {
            return base.Channel.GetPolygon(guid);
        }
        
        public PheonixRt.DataContracts.SurfaceMeshDataContract GetSurfaceMesh(System.Guid id) {
            return base.Channel.GetSurfaceMesh(id);
        }
        
        public PheonixRt.DataContracts.SurfaceMeshDataContract GetSurfaceMeshByRelatedStructureId(System.Guid relatedId) {
            return base.Channel.GetSurfaceMeshByRelatedStructureId(relatedId);
        }
        
        public PheonixRt.DataContracts.SurfaceMeshDataContract AddSurfaceMesh(PheonixRt.DataContracts.SurfaceMeshDataContract sdc) {
            return base.Channel.AddSurfaceMesh(sdc);
        }
        
        public void RemoveSurfaceMesh(System.Guid guid) {
            base.Channel.RemoveSurfaceMesh(guid);
        }
    }
}
