//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PheonixRt.Mvvm.ResampleManagerServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResampleManagerServiceReference1.IResampleManager")]
    public interface IResampleManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IResampleManager/ResampleImageVolume")]
        void ResampleImageVolume(PheonixRt.ResampleServiceContracts.ImageVolumeResampleRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResampleManagerChannel : PheonixRt.Mvvm.ResampleManagerServiceReference1.IResampleManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResampleManagerClient : System.ServiceModel.ClientBase<PheonixRt.Mvvm.ResampleManagerServiceReference1.IResampleManager>, PheonixRt.Mvvm.ResampleManagerServiceReference1.IResampleManager {
        
        public ResampleManagerClient() {
        }
        
        public ResampleManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResampleManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResampleManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResampleManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ResampleImageVolume(PheonixRt.ResampleServiceContracts.ImageVolumeResampleRequest request) {
            base.Channel.ResampleImageVolume(request);
        }
    }
}
